// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAAraHhecUhykO5e06ROrQ9Z6-E_Ryhg',
    appId: '1:878963803359:web:d518f17caa70ed027d156a',
    messagingSenderId: '878963803359',
    projectId: 'xpensiq',
    authDomain: 'xpensiq.firebaseapp.com',
    storageBucket: 'xpensiq.firebasestorage.app',
    measurementId: 'G-82MG6ZRPTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vveffUXepNo6RQiVxbabXsBpzzmWenU',
    appId: '1:878963803359:android:041e5f3bd98045b57d156a',
    messagingSenderId: '878963803359',
    projectId: 'xpensiq',
    storageBucket: 'xpensiq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qF9xOpzh9oHhLLACvdPNlaAnFkVP6Bg',
    appId: '1:878963803359:ios:3d0ba2204fc57b7d7d156a',
    messagingSenderId: '878963803359',
    projectId: 'xpensiq',
    storageBucket: 'xpensiq.firebasestorage.app',
    iosBundleId: 'com.example.xpensiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3qF9xOpzh9oHhLLACvdPNlaAnFkVP6Bg',
    appId: '1:878963803359:ios:3d0ba2204fc57b7d7d156a',
    messagingSenderId: '878963803359',
    projectId: 'xpensiq',
    storageBucket: 'xpensiq.firebasestorage.app',
    iosBundleId: 'com.example.xpensiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAAraHhecUhykO5e06ROrQ9Z6-E_Ryhg',
    appId: '1:878963803359:web:71b327ca328b16bf7d156a',
    messagingSenderId: '878963803359',
    projectId: 'xpensiq',
    authDomain: 'xpensiq.firebaseapp.com',
    storageBucket: 'xpensiq.firebasestorage.app',
    measurementId: 'G-CQWGQSM86Y',
  );
}
